[[ruby-on-rails-security-guide]]
== Ruby on Rails 安全指南
:imagesdir: ../images
:numbered:

// chinakr 翻译

[.chapter-abstract]
--
本文介绍 Web 应用中常见的安全问题，以及如何在 Rails 中避免这些问题。

读完本文后，您将学到：

* 所有需要强调的安全对策；
* Rails 中会话的概念，应该在会话中保存什么内容，以及常见的攻击方式；
* 为什么访问网站也可能带来安全问题（跨站请求伪造）；
* 处理文件或提供管理界面时需要注意的问题；
* 如何管理用户：登录、退出，以及不同层次上的攻击方式；
* 最常见的注入攻击方式。
--

[[introduction]]
=== 序言

Web 应用框架的作用是帮助开发者创建 Web 应用。其中一些框架还能帮助我们提高 Web 应用的安全性。事实上，框架之间无所谓谁更安全，对于许多框架来说，只要使用正确，我们都能开发出安全的应用。Ruby on Rails 提供了一些十分智能的辅助方法，例如，用于防止 SQL 注入的辅助方法，极大减少了这一安全风险。

一般来说，并不存在什么即插即用的安全机制。安全性取决于开发者如何使用框架，有时也取决于开发方式。安全性还取决于 Web 应用环境的各个层面，包括后端存储、Web 服务器和 Web 应用自身等（甚至包括其他 Web应用）。

不过，据高德纳咨询公司（Gartner Group）估计，75% 的攻击发生在 Web 应用层面，报告称“在进行了安全审计的 300 个网站中，97% 存在被攻击的风险”。这是因为针对 Web 应用的攻击相对来说更容易实施，其工作原理和具体操作都比较简单，即使是非专业人士也能发起攻击。

针对 Web 应用的安全威胁包括账户劫持、绕过访问控制、读取或修改敏感数据，以及显示欺诈信息等。有时，攻击者还会安装木马程序或使用垃圾邮件群发软件，以便获取经济利益，或者通过纂改公司资源来损害品牌形象。为了防止这些攻击，最大限度降低或消除攻击造成的影响，首先我们必须全面了解各种攻击方式，只有这样才能找出正确对策——这正是本文的主要目的。

为了开发安全的 Web 应用，我们必须从各个层面紧跟安全形势，做到知己知彼。为此，我们可以订阅安全相关的邮件列表，阅读相关博客，同时养成及时更新并定期进行安全检查的习惯（请参阅 <<additional-resources>>）。这些工作都是手动完成的，只有这样我们才能发现潜在安全隐患。

[[sessions]]
=== 会话
